version: '2'
services:
    configurator-mysql:
#        image: mysql:5.7.20
        image: mysql:8.0.19
        # volumes:
        #     - ~/volumes/jhipster/configurator/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=mysql
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
#            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=configurator
            - MYSQL_ROOT_HOST=%
        expose:
            - 1306
        ports:
#            - 3306:3306
#            - 1306:1306
            - 1306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
